
version: "2"

services:

   app:
      build: ./src
      links:
        - db
      ports:
        - "5000:5000"
      volumes:
        - ./src:/app/.

   db:
      image: mysql:8
      ports:
        - "5001:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro